title: OneMeatNobodyCanBeat
description: Stock projection and analysis files
baseurl: ""
url: https://staging.d3bzsmonofa3d5.amplifyapp.com/

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - node_modules/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
